apiVersion: apps/v1
kind: Deployment
metadata:
  name: enumerator
  labels:
    app: backend

spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: demo-kubernate-api:dev
          name: enumerator
          ports:
            - containerPort: 8081